apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: scraper-app
spec:
  type: ClusterIP
  selector:
    app: backend-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080