apiVersion: v1
kind: Secret
metadata:
  name: scraper-secret
  namespace: scraper-app
type: Opaque
stringData:
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
  SPRING_DATASOURCE_USERNAME: scraper
  SPRING_DATASOURCE_PASSWORD: scraper
  POSTGRES_DB: scraperdb
  POSTGRES_USER: scraper
  POSTGRES_PASSWORD: scraper
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin