services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: scraper-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16
    container_name: scraper-postgres
    environment:
      POSTGRES_DB: Scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-api:
    build: ./backend-api
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Scrapper
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - rabbitmq
      - postgres

  frontend:
    build: ./frontend
    container_name: scraper-frontend
    ports:
      - "5500:80"
    depends_on:
      - backend-api
  
  worker-a:
    build: ./worker-a
    container_name: scraper-worker-a
    environment:
      RABBITMQ_HOST: rabbitmq
      QUEUE_NAME: scraping.jobs
      RESULTS_QUEUE: scraping.results
      RETRY_QUEUE: scraping.jobs.retry
      DLQ_QUEUE: scraping.jobs.dlq
      MAX_ATTEMPTS: 3
    depends_on:
      - rabbitmq

volumes:
  postgres_data: