apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: scraper-app
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - name: web
      port: 3000
      targetPort: 3000